baseURL = "https://sarju88.github.io/credentials/"
languageCode = "en-us"
title = "Credentials"
theme = "ananke"

[params]
  # Ananke theme settings
  showPoweredBy = true
  showSocialLinks = true
  showLanguageSelector = true
